"""coin and market_pair

Revision ID: 21250892261a
Revises: 9490f64daef0
Create Date: 2026-03-12 00:35:12.271827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21250892261a'
down_revision: Union[str, Sequence[str], None] = '9490f64daef0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coins_symbol'), 'coins', ['symbol'], unique=True)
    op.create_table('market_pairs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('base_coin_id', sa.UUID(), nullable=False),
    sa.Column('quote_coin_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['base_coin_id'], ['coins.id'], ),
    sa.ForeignKeyConstraint(['quote_coin_id'], ['coins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_pairs_symbol'), 'market_pairs', ['symbol'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_pairs_symbol'), table_name='market_pairs')
    op.drop_table('market_pairs')
    op.drop_index(op.f('ix_coins_symbol'), table_name='coins')
    op.drop_table('coins')
    # ### end Alembic commands ###
